---
# see: https://github.com/ansible/ansible-modules-core/issues/2951
- name: Update apt cache using apt module
  apt: update_cache=yes cache_valid_time=7200
  delay: 1
  ignore_errors: yes
  register: apt_result
  retries: 2
  until: apt_result|success
  become: yes
  become_user: root
  become_method: sudo

- name: Clean apt cache when apt module failed
  shell: "{{ item }}"
  with_items:
  #- "apt-get update --fix-missing"
  - "apt-get clean"
  - "rm -vrf /var/lib/apt/lists/*"
  - "mkdir /var/lib/apt/lists/partial"
  when: apt_result|failed
  become: yes
  become_user: root
  become_method: sudo

- name: Retry if needed using command apt-get update
  shell: apt-get update
  ignore_errors: yes
  when: apt_result|failed
  become: yes
  become_user: root
  become_method: sudo
