---
- name: Add EPEL YUM repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://getfedora.org/static/352C64E5.txt
    gpgcheck: yes
    # see: https://getfedora.org/keys/
  become: yes
  become_user: root
  become_method: sudo

- name: Install dependencies by yum
  yum:
      name={{ item }}
      update_cache=yes
  with_items:
  - device-mapper-persistent-data
  - aria2
  - bzip2
  - curl
  - git
  - jq
  - lvm2
  - python-devel
  - python-setuptools
  - tar
  - unzip
  - yum-utils
  - zip
  become: yes
  become_user: root
  become_method: sudo
