---
# python 2.6 has SNI/SSL issue even when required libs installed
#- name: easy_install pip
#  easy_install:
#    executable: /usr/bin/easy_install
#    name: pip
#
#- name: pip urllib3
#  pip:
#    executable: /usr/local/bin/pip2
#    name: urllib3
#- name: pip pyOpenSSL
#  pip:
#    executable: /usr/local/bin/pip2
#    name: pyOpenSSL
#- name: pip ndg-httpsclient
#  pip:
#    executable: /usr/local/bin/pip2
#    name: ndg-httpsclient
#- name: pip pyasn1
#  pip:
#    executable: /usr/local/bin/pip2
#    name: pyasn1

# see: https://github.com/ansible/ansible/issues/12161
- name: find python version
  shell: python2 --version 2>&1 | awk '{print $2}' || python --version 2>&1 | awk '{print $2}'
  register: python_version

- debug: msg="python_version {{ python_version.stdout }}"

- name: test python >= 2.7.9 installed
  shell: dpkg --compare-versions {{ python_version.stdout }} ge 2.7.9
  ignore_errors: yes
  register: is_python_version_ok

- name: add key for ppa python repository
  apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present
  become: yes
  become_user: root
  become_method: sudo
  when: is_python_version_ok|failed

- name: Add ppa python repository
  apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present #update_cache=yes
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: yes
  when: is_python_version_ok|failed

- name: Clean apt cache for ppa repository
  shell: "{{ item }}"
  with_items:
  - "apt-get clean"
  - "rm -vrf /var/lib/apt/lists/*"
  - "mkdir /var/lib/apt/lists/partial"
  sudo: yes
  when: is_python_version_ok|failed

- name: Update apt cache for ppa repository
  ignore_errors: yes
  shell: apt-get update
  sudo: yes
  when: is_python_version_ok|failed

- name: ensure python2.7 latest is installed
  apt:
    pkg: python2.7
    state: latest
    install_recommends: no
  become: yes
  become_user: root
  become_method: sudo
  when: is_python_version_ok|failed

- name: ensure python2.7-dev latest is installed
  apt:
    pkg: python2.7-dev
    state: latest
    install_recommends: no
  become: yes
  become_user: root
  become_method: sudo
  when: is_python_version_ok|failed

- name: ensure python2.7 python2.7-dev latest is installed
  shell: "{{ item }}"
  whith_items:
  - "apt-get install python2.7 python2.7-dev -y"
  become: yes
  become_user: root
  become_method: sudo

# sudo add-apt-repository --remove ppa:fkrull/deadsnakes

# stuck on python-apt module
#- name: Update apt cache for install python 2.7.12
#  ignore_errors: yes
#  shell: apt-get update
#  sudo: yes
#  when: is_python_version_ok|failed
#
#- name: install python 2.7.12
#  shell: "{{ item }}"
#  with_items:
#  - "apt-get install build-essential checkinstall -y"
#  - "apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y"
#  - "curl SL- https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz | tar xzv -C /tmp"
#  - "cd /tmp/Python-2.7.12 && ./configure --enable-ipv6 && make install"
#  sudo: yes
#  when: is_python_version_ok|failed
#
#- name: python 2.7.12 setup
#  shell: "{{ item }}"
#  with_items:
#  - "ln -sf /usr/local/bin/python2.7 /usr/bin/python2"
#  - "ln -sf /usr/local/bin/python2.7 /usr/bin/python"
#  - "ln -sf /usr/local/bin/python2.7-config /usr/bin/python2-config"
#  - "ln -sf /usr/local/bin/python2.7-config /usr/bin/python-config"
#  - "wget https://bootstrap.pypa.io/ez_setup.py -O - | /usr/local/bin/python2.7"
#  - "ln -sf /usr/local/bin/easy_install-2.7 /usr/bin/easy_install-2.7"
#  - "ln -sf /usr/local/bin/easy_install /usr/bin/easy_install"
#  - "/usr/local/bin/easy_install pip"
#  - "ln -sf /usr/local/bin/pip2.7 /usr/bin/pip2.7"
#  - "ln -sf /usr/local/bin/pip2 /usr/bin/pip2"
#  - "ln -sf /usr/local/bin/pip /usr/bin/pip"
#  - "/usr/local/bin/pip install virtualenv"
#  - "pip install "
