---
- include: "apt-get-update.yml"
  static: no

- stat:
    path: /usr/local/bin/pip2
  register: usr_local_bin_pip2

- name: Install dependencies by apt
  apt:
    name={{ item }}
    #update_cache=yes
  with_items:
  - apt-transport-https
  - aria2
  - bzip2
  - ca-certificates
  - curl
  - git
  - jq
  - python-dev
  - python-setuptools
  #- python-distutils-extra
  - software-properties-common
  - tar
  - unzip
  - zip
  become: yes
  become_user: root
  become_method: sudo
