---
- debug: msg="ansible_architecture {{ ansible_architecture }}, ansible_os_family {{ ansible_os_family }}, ansible_distribution {{ ansible_distribution }}"
- debug: msg="ansible_distribution_release {{ ansible_distribution_release }}, ansible_distribution_version {{ ansible_distribution_version }}"

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: "deps-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  static: no
  when: ansible_distribution_release == "trusty"

- include: "deps-{{ ansible_os_family }}.yml"
  static: no

# The docker_container and docker_image module in Ansible
# requires docker-py library to be installed on the remote server,
# so at first we use python-pip to install docker-py library on all servers before installing the Docker:
- name: Install pip
  easy_install:
    name=pip
  when: https_proxy is not defined or https_proxy == ""
- name: Install pip
  environment:
    https_proxy: "{{ https_proxy }}"
  shell: easy_install pip
  when: https_proxy is defined and https_proxy != ""
- name: Install docker-py
  pip:
    state=present
    name=docker
    version=2.4.2
    #name=docker-py
    #version=1.10.6
  when: https_proxy is not defined or https_proxy == ""
- name: Install docker-py
  environment:
    https_proxy: "{{ https_proxy }}"
  shell: pip2 install docker==2.4.2
  when: https_proxy is defined and https_proxy != ""

- include: "docker-engine-{{ ansible_distribution }}.yml"
  static: no

- include: "docker-machine.yml"
  static: no

- include: "docker-compose.yml"
  static: no

# Create a system group for Docker
# and add any user defined in “docker_users” variable to this group,
# and it will copy template for Docker configuration then restart Docker.
- name: Create a docker group
  group:
    name=docker
    state=present

- name: Add user(s) to docker group
  user:
    name={{ item }}
    group=docker
    state=present
  with_items: docker_users
  when: docker_users is defined

- name: Create oss-network
  docker_network:
    name: oss-network
  when: create_oss_network
